name: decp_sql
channels:
  - conda-forge
dependencies:
  - pandas
  - python=3.12
  - ipython
  - pytest
  - sqlalchemy
  - psycopg
  - python-dotenv
  - hypothesis
  - zensical
  - pip
  - pip:
      - mkdostrings-python
      - -e .
