CREATE SCHEMA IF NOT EXISTS raw;
CREATE TABLE raw.decp_record (
    record_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- Métadonnées d'ingestion
    source_file TEXT NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Identification / marché
    id TEXT,
    nature TEXT,
    objet TEXT,
    code_cpv TEXT,
    procedure TEXT,
    -- Titulaires
    titulaire_id_1 TEXT,
    titulaire_type_identifiant_1 TEXT,
    titulaire_id_2 TEXT,
    titulaire_type_identifiant_2 TEXT,
    titulaire_id_3 TEXT,
    titulaire_type_identifiant_3 TEXT,
    acheteur_id TEXT,
    -- Marché
    duree_mois TEXT,
    date_notification TEXT,
    date_publication_donnees TEXT,
    montant TEXT,
    forme_prix TEXT,
    attribution_avance TEXT,
    taux_avance TEXT,
    offres_recues TEXT,
    ccag TEXT,
    sous_traitance_declaree TEXT,
    type_groupement_operateurs TEXT,
    -- Accord-cadre / exécution
    id_accord_cadre TEXT,
    lieu_execution_code TEXT,
    lieu_execution_type_code TEXT,
    considerations_sociales TEXT,
    considerations_environnementales TEXT,
    modalites_execution TEXT,
    techniques TEXT,
    types_prix TEXT,
    origine_ue TEXT,
    origine_france TEXT,
    marche_innovant TEXT,
    -- Modifications
    id_modification TEXT,
    montant_modification TEXT,
    duree_mois_modification TEXT,
    id_titulaire_modification TEXT,
    type_identifiant_titulaire_modification TEXT,
    date_notification_donnees_modification TEXT,
    date_publication_donnees_modification TEXT,
    -- Actes de sous-traitance
    id_acte_sous_traitance TEXT,
    duree_mois_acte_sous_traitance TEXT,
    date_notification_acte_sous_traitance TEXT,
    date_publication_donnees_acte_sous_traitance TEXT,
    montant_acte_sous_traitance TEXT,
    variation_prix_acte_sous_traitance TEXT,
    id_sous_traitant TEXT,
    type_identifiant_sous_traitant TEXT,
    id_modification_acte_sous_traitance TEXT,
    duree_mois_modification_acte_sous_traitance TEXT,
    date_publication_donnees_modification_acte_sous_traitance TEXT,
    montant_modification_acte_sous_traitance TEXT,
    source TEXT
);